#ignore AssemblyInfo changes in git
git update-index --skip-worktree "CSharpApp\buildThisFirst\My Project\AssemblyInfo.cs"
git update-index --skip-worktree "CSharpApp\BusinessLogic\My Project\AssemblyInfo.cs"
git update-index --skip-worktree "CSharpApp\CadDevTools\Properties\AssemblyInfo.cs"
git update-index --skip-worktree "CSharpApp\MainApp\My Project\AssemblyInfo.cs"
git update-index --skip-worktree "CSharpApp\Plugin\Properties\AssemblyInfo.cs"
git update-index --skip-worktree "VbNetApp\buildThisFirst\My Project\AssemblyInfo.vb"
git update-index --skip-worktree "VbNetApp\BusinessLogic\My Project\AssemblyInfo.vb"
git update-index --skip-worktree "VbNetApp\CadDevTools\My Project\AssemblyInfo.vb"
git update-index --skip-worktree "VbNetApp\MainApp\My Project\AssemblyInfo.vb"
git update-index --skip-worktree "VbNetApp\Plugin\My Project\AssemblyInfo.vb"
